name: Build and Push arm64 Docker Image to Oracle Container Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Oracle Container Registry
    - name: Log in to Oracle Container Registry
      env:
        OCI_USERNAME: ${{ secrets.OCI_USERNAME }}
        OCI_API_KEY: ${{ secrets.OCI_API_KEY }}
      run: |
        echo $OCI_API_KEY | docker login -u $OCI_USERNAME --password-stdin ocir.uk-london-1.oci.oraclecloud.com

    # Build and push arm64 Docker image
    - name: Build and Push arm64 Docker Image
      run: |
        docker buildx build \
          --platform linux/arm64 \
          --tag ocir.uk-london-1.oci.oraclecloud.com/lrwuubtwxjma/constellation-images/jonno-personal-frontend:latest \
          --push .
